colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["news"]

disableImageOptimization = false

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed"

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "news"
  cardView = false

[article]
  showDate = true
  showAuthor = false
  showHero = false
  showBreadcrumbs = true
  showDraftLabel = false
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = false
  showTaxonomies = false
  showWordCount = false
  sharingLinks = []
  showZenMode = false

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []
